name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies (client)
      run: |
        cd client
        npm install

    - name: Build client
      run: |
        cd client
        npm run build

    - name: Install dependencies (server)
      run: |
        cd server
        npm install

    - name: Deploy to GitHub Pages (client)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/build

    - name: Deploy to Heroku (server)
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        cd server
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy to Heroku"
        heroku git:remote -a your-heroku-app-name
        git push heroku main --force
